### ISSUE TITLE
Remove convenience functions (`disk`, `circle`, etc.)

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/Domains.jl#29]
There are too many convenience functions, which goes against a good practice code design principle that there should only be one way to write anything (to make find-and-replace easier, etc.). I think _all_ the lowercase convenience functions can be removed: `UnitDisk` is just as good as `disk`, etc.

**Comment by dlfivefifty** [comment]
Ah, I see, they are used because the domains are mapped domains.

**Comment by dlfivefifty** [comment]
Though I think my point is still correct: `2*UnitBall()` is arguably clearer than `ball(2)`.

**Comment by daanhb** [comment]
In the absence of a type that stores a centre and radius, it seemed user-friendly to provide a routine that would return a domain that represents what the user wants. They are lower-cased because you can't predict which type they return. Right now they are indeed mapped domains. How about `ball(radius=2)`?
But I agree there shouldn't be too many of these.

**Comment by dlfivefifty** [comment]
I think ` 2UnitBall() ` is pretty user friendly

**Comment by dlfivefifty** [comment]
Some will need to stay for now: e.g. `ellipse`
